/* All free solid fontawesome icons -> https://fontawesome.com/icons?d=gallery&s=solid&m=free */

import {
    faAngleDown,
    faCalendarAlt,
    faAngleRight,
    faArrowLeft,
    faBars,
    faBookOpen,
    faChartArea,
    faChartBar,
    faCalendarPlus,
    faCalendarCheck,
    faInfoCircle,
    faAddressCard,
    faChartPie,
    faChevronDown,
    faChevronUp,
    faColumns,
    faSearch,
    faTable,
    faTachometerAlt,
    faUser,
} from '@fortawesome/free-solid-svg-icons';

export const fontAwesomeSolidIcons = {
    faAngleDown,
    faAngleRight,
    faArrowLeft,
    faCalendarCheck,
    faInfoCircle,
    faAddressCard,
    faBars,
    faBookOpen,
    faChartArea,
    faChartBar,
    faChartPie,
    faChevronDown,
    faCalendarPlus,
    faChevronUp,
    faColumns,
    faSearch,
    faCalendarAlt,
    faTable,
    faTachometerAlt,
    faUser,
};
